// Generated by CoffeeScript 1.6.3
(function() {
  var candidate, casper, secret, url;

  casper = (require('casper')).create();

  secret = require('./secret');

  url = 'https://club.nintendo.jp/member/exec/index';

  candidate = [];

  casper.on('remote.message', function(message) {
    return this.echo('remote message: ' + message);
  }).start(url, function() {
    this.echo(this.getCurrentUrl());
    return this.fill('form[name="EntranceForm"]', {
      'memberid': secret.getMemberId(),
      'memberpass': secret.getMemberPassword()
    }, true);
  }).then(function() {
    return this.echo(this.getCurrentUrl());
  }).thenClick('a[href="./memberEnqueteInfo"]', function() {
    var list, x, _i, _len;
    this.echo(this.getCurrentUrl());
    list = this.evaluate(function() {
      var i, nodes, _i, _ref;
      nodes = document.querySelectorAll('td:nth-child(2)');
      list = [];
      for (i = _i = 0, _ref = nodes.length; 0 <= _ref ? _i < _ref : _i > _ref; i = 0 <= _ref ? ++_i : --_i) {
        if (/.*\uff5e.*/.exec(nodes[i].textContent) !== null) {
          list.push(i);
        }
      }
      return console.log(JSON.stringify(list));
    });
    for (_i = 0, _len = list.length; _i < _len; _i++) {
      x = list[_i];
      this.echo(x.textContent);
    }
  });

  casper.run();

}).call(this);
